### ISSUE TITLE
Unable to save less files automatically

### ISSUE THREAD

**Issue by saikete** [askfiy/neovim-easy-less#2]
I set the plug-in configuration according to the content in the document, and installed the less plug-in globally in the system, but when I saved the file ending with .less, nothing happened.

**Comment by askfiy** [comment]
Essentially, this plug-in only automatically runs the "lessc" command after saving the LESS file. You should check whether the "lessc" command is normal first.

**Comment by askfiy** [comment]
> Essentially, this plug-in only automatically runs the "lessc" command after saving the LESS file. You should check whether the "lessc" command is normal first.

**Comment by saikete** [comment]
<img width="775" alt="image" src="https://github.com/askfiy/neovim-easy-less/assets/45237450/66fc904c-891b-4fd6-851c-a76e7804d4de">
Yes! I'm sure it exists in my environment

**Comment by askfiy** [comment]
Maybe you can provide me with your configuration and I can check it for you.

**Comment by saikete** [comment]
Thank you so much! It's right here, my custom branch：
https://github.com/saikete/nvim/tree/custom

**Comment by askfiy** [comment]
我认为问题应该是“非常懒惰”。删除此“事件”。

When you specify "ft", you no longer need "event".

**Comment by saikete** [comment]
thanks very much, so now I have deleted the field with event="veryLazy" and I am inside a less file, should I run the lessc command? I found that my local directory did not generate a .css file

**Comment by askfiy** [comment]
Unexpectedly, can you manually generate the css file via the 'lessc' command?

What is the output of the following commands?

```shell
$ npm -g list
```

If everything works fine, it should automatically generate a css file after you input ':w'.

**Comment by saikete** [comment]
<img width="520" alt="image" src="https://github.com/askfiy/neovim-easy-less/assets/45237450/15ff5cc7-8a49-4072-b345-8f6ff9f1c3e6">
This is my screenshot, nothing happens after I save it now

**Comment by askfiy** [comment]
Have you ever tried to manually run the "lessc" command to generate css files?

Example:

```shell
$ lessc index.less index.css
```

**Comment by saikete** [comment]
yes it works fine
